esudo: false
branches:
  only:
  - develop
language: node_js
node_js:
- '10'
before_install:
#-s -- --version 0.27.5
- 'pwd && ls -als'
#- 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly'
#- 'export PATH="$HOME/.yarn/bin:$PATH"'
#cache:
#  yarn: true
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
#- 'yarn --version'
#- 'yarn install --ignore-engines'
- 'npm --version'
- 'npm install'
script:
- 'npm run now'
- 'npx now alias --token=$NOW_TOKEN $(npx now ./now --no-clipboard --token=$NOW_TOKEN --public) readium2.now.sh'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
